version: "3.7"
services:
    
    # This redis without auth is for local dev
    portfolio-redis:
        image: redis:latest
        ports:
            - 6379:6379
        container_name: portfolio-redis

    # This db is just for local development.
    portfolio-postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: portfolio
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432
        volumes:
            - ./persistence/postgres:/data/postgres
        container_name: portfolio-postgres

    # The django API
    portfolio-backend:
        build: .
        image: portfolio-backend:latest
        ports:
            - 8000:8000
        volumes:
            - .:/backend
        depends_on:
            - portfolio-redis
            - portfolio-postgres
        container_name: portfolio-backend
