name: Test Backend

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Test with pytest
      run: |
        export GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        export REDIS_URL=${{ secrets.REDIS_URL }}
        pytest
